accounts/urls.py
from django.urls import path
from .views import SignUpView, SignUpSuccessView
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup_success/', SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'),),
    path('dashboard/', include('dashboard.urls'),)
]

dashboard/urls.py
from django.urls import path
from .views import DashboardView

app_name = 'dashboard'
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

dashboard/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

class CustomUserUpdateForm(UserChangeForm):
    pass

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy

from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    template_name = 'accounts/signup_success.html'

dashboard/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class DashboardView(TemplateView):
    template_name = 'dashboard/index.html'

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}ログイン{% endblock %}

{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
{% endblock %}
{% block content %}
{% if form.errors %}
    <p style="color: red">ユーザー名とパスワードが一致しません。</p>
    {% endif %}
    {% if user.is_authenticated %}
    <h2>すでにログインしています。</h2>
    {% else %}
    <div class="formContainer">
        <form method="post">
            {% csrf_token %}
            <h1>ログインフォーム</h1>
            <hr />
            <div class="uiForm">
                <div class="formField">
                    <label for="username">ユーザー名:</label>
                    <input type="text" placeholder="ユーザー名" id="username">
                </div>
                <div class="formField">
                    <label for="password">パスワード:</label>
                    <input type="password" placeholder="パスワード" id="password">
                </div>
                <button class="submitButton">ログイン</button>
            </div>
        </form>
    </div>
    {% endif %}
{% endblock %}

 
<body>
    
</body>
</html>

templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ログアウト</title>
</head>
<body>
    <h3>ログアウトしました</h3>
    <a href="{% url 'accounts:login' %}">ログインページ</a>
</body>
</html>

templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}サインナップ{% endblock %}

{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/css/signup.css' %}">
{% endblock %}

{% block content %}
<div class="formContainer">
    <form method="post">
        {% csrf_token %}
        <h1>サインナップ</h1>
        <hr />
        <div class="uiForm">
            {% for field in form %}
            <div class="formField">
                {{ field.label_tag}}
                {{ field }}
            </div>
            {% for error in field.errors %}
            <p style="color:red">{{ error }}</p>
            {% endfor %}
            {% endfor %}
            <button class="submitButton">サインナップ</button>
        </div>
    </form>
</div>
{% endblock %}

templates/accounts/signup_success.html
{% extends "base.html" %}
{% block content %}
<h2>ユーザー登録完了しました。</h2>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ja">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
    {% block styles %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav>Navigation Bar</nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        
    </footer>
</body>
</html>

templates/dashboard/index.html
{% extends "base.html" %}

{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
{% endblock %}

{% block title %}KPI速報{% endblock %}

{% block content %}
<div class="page">
    <div class="sidebar">
        <div class="sidebarContainer">
            <h5>test</h5>
            <h5>test</h5>
            <h5>test</h5>
        </div>
    </div>
    <div class="contents">
        <div class="titleContainer">
            <h1>KPI速報</h1>
            <div class="timeContainer">
                <div class="timeBox">
                    <h5>現在の時刻</h5>
                    <div class="timeContent">00:00:00</div>
                </div>
                <div class="timeBox">
                    <h5>20分前の時刻</h5>
                    <div class="timeContent">00:00:00</div>
                </div>
                <div class="timeBox">
                    <h5>40分前の時刻</h5>
                    <div class="timeContent">00:00:00</div>
                </div>
            </div>
        </div>
        <div class="itemContainer">
            <div class="containerRow">
                <div class="box">
                    <h5>ACW</h5>
                    <div class="contentField">
                        <div class="content">
                            <p class="mainContent">00:00:00</p>
                        </div>
                    </div>
                </div>
                <div class="box">
                    <h5>ACW</h5>
                    <div class="contentField">
                        <div class="content">
                            <p class="mainContent">00:00:00</p>
                        </div>
                    </div>
                </div>
                <div class="box">
                    <h5>電話問い合わせ件数</h5>
                    <div class="contentField">
                        <div class="content">
                            <p class="mainContent">0 件</p>
                        </div>
                    </div>
                </div>
                <div class="box">
                    <h5>応答率</h5>
                    <div class="contentField">
                        <div class="content">
                            <p class="mainContent">0.0 %</p>
                            <p class="subContent">0 / 0</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="containerRow">
                <div class="box">
                    <h5>直受け率</h5>
                    <div class="contentField">
                        <div class="content">
                            <p class="mainContent">0.0 %</p>
                            <p class="subContent">0 / 0</p>
                            <p class="subContent">Buffer: 0</p>
                        </div>
                    </div>
                </div>
                <div class="box">
                    <h5>20分以内折返し率</h5>
                    <div class="contentField">
                        <div class="content">
                            <p class="mainContent">0.0 %</p>
                            <p class="subContent">0 / 0</p>
                            <p class="subContent">Buffer: 0</p>
                        </div>
                    </div>
                </div>
                <div class="box">
                    <h5>30分以内折返し率</h5>
                    <div class="contentField">
                        <div class="content">
                            <p class="mainContent">0.0 %</p>
                        </div>
                        <div class="content">
                            <p class="subContent">0 / 0</p>
                        </div>
                    </div>
                </div>
                <div class="box">
                    <h5>40分以内折返し率</h5>
                    <div class="contentField">
                        <div class="content">
                            <p class="mainContent">0.0 %</p>
                            <p class="subContent">0 / 0</p>
                            <p class="subContent">Buffer: 0</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}